import type { Metadata } from "next";
import "../styles/global.css";
import ClientLayout from "./ClientLayout"; // Import the client component

export const metadata: Metadata = {
  title: "Ceylon Rich",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative">
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
