import type { Metadata } from "next";
import "../styles/global.css";
import { CartProvider } from "@/contexts/CartContext";
import { SessionProvider } from "next-auth/react";
import { Footer, Navbar } from "@/layouts";
import { AuthProvider } from "@/layouts/Authcontext";

export const metadata: Metadata = {
  title: "Ceylon Rich",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}>
        <AuthProvider>
          <SessionProvider>
            <CartProvider>
              <Navbar />
              {children}
              <Footer />
            </CartProvider>
          </SessionProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
